name=AMPX Modbus TCP/IP
version=1.0.0
author=AMPX
maintainer=AMPX <info@ampx.co>
sentence=Library for Modbus TCP/IP communication over Ethernet.
paragraph=Provides functions for reading data from energy meters and other Modbus devices over TCP/IP Ethernet connections.
category=Communication
url=https://github.com/ampx/ampx_modbus_tcpip
architectures=*
depends=Ethernet
includes=ampx_modbus_tcpip.h 